In [1]:
import numpy as np
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [2]:
arr.shape = (2, 4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [3]:
arr = np.arange(8)
arr_new = arr.reshape((2, 4), order='F')
print(arr_new)
print('Locker:')
arr.shape = (4, 2)
print(arr)
arr_trans = arr_new.transpose()
print('Transport:')
print(arr_trans)

[[0 2 4 6]
 [1 3 5 7]]
Locker:
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
Transport:
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [4]:
arr_new.transpose()
arr_new

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [5]:
arr = np.arange(3)
arr_trans = arr.transpose()
print(arr_trans)

[0 1 2]


In [6]:
arr = np.linspace(0, 6, 12, endpoint=False).reshape(3, 4)
print(arr)

[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]


In [7]:
print(arr[1, 2])

3.0


In [8]:
print(arr[:2, 2])

[1. 3.]


In [9]:
arr[1:, 2:4]

array([[3. , 3.5],
       [5. , 5.5]])

In [10]:
arr[:2]

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5]])

In [11]:
arr = np.array([23,12,45,12,23,4,15,3])
arr_new = np.sort(arr)
print(arr)
print(arr_new)

[23 12 45 12 23  4 15  3]
[ 3  4 12 12 15 23 23 45]


In [12]:
arr = np.array([23,12,45,12,23,4,15,3])
print(arr.sort())
print(arr)

None
[ 3  4 12 12 15 23 23 45]


In [13]:
data = np.array([4, 9, -4, 3])
print(type(data))
roots = np.sqrt(data)
print(data)
print(roots)

<class 'numpy.ndarray'>
[ 4  9 -4  3]
[2.         3.                nan 1.73205081]


/tmp/ipykernel_3634/949364484.py:3: RuntimeWarning: invalid value encountered in sqrt
  roots = np.sqrt(data)


In [14]:
isn = np.isnan(roots)
print(type(isn))

<class 'numpy.ndarray'>


In [15]:
#tf = [True, True, False, False]
print(roots[2])
print(roots)

nan
[2.         3.                nan 1.73205081]


In [16]:
roots[np.isnan(roots)] = 0
print(roots)

[2.         3.         0.         1.73205081]


In [17]:
sum(roots)

6.732050807568877

In [18]:
vec1 = np.array([2,4,7,5])
print(vec1.dtype)
vec2 = np.array([12,6,3.5,1])
list1 = [1,2,3,4]
list2 = [5,6,7,8]
print(list1 * 3)

int64
[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]


In [19]:
vec1[vec1 <= 6]

array([2, 4, 5])

In [20]:
vec = np.array([3, 4])
l = [3, 6]

In [21]:
print(type(np.linalg.norm(l)))

<class 'numpy.float64'>
