In [1]:
import numpy as np

In [2]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
arr

array([ 1,  5,  2,  9, 10], dtype=int8)

In [3]:
arr[2] = 3001
arr

array([  1,   5, -71,   9,  10], dtype=int8)

In [4]:
arr[2] = '45'
arr

array([ 1,  5, 45,  9, 10], dtype=int8)

In [5]:
arr.ndim

1

In [6]:
zeros_3d = np.zeros((4,3,2))
zeros_3d

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [7]:
zeros_3d.size

24

In [10]:
arr = np.linspace(1,4,10)
arr

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ])